"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['/Users/aale/Documents/Projects/ALFRED-Revival/ALFRED Revival.py']
DATA_FILES = ['/Users/aale/Documents/Projects/ALFRED-Revival/connected.png',
 '/Users/aale/Documents/Projects/ALFRED-Revival/noconnect.png',
              '/Users/aale/Documents/Projects/ALFRED-Revival/png.pickle',
              '/Users/aale/Documents/Projects/ALFRED-Revival/user_settings.json',
              '/Users/aale/Documents/Projects/ALFRED-Revival/default_settings.json',
              '/Users/aale/Documents/Projects/ALFRED-Revival/png.pickle']
OPTIONS = {'iconfile': '/Users/aale/Documents/Projects/ALFRED-Revival/phoenix.icns',
           'packages': 'mysql',
           'plist': '/Users/aale/Desktop/Info.plist',
           'arch': 'universal2'}

setup(
    app=APP,
    version='1.3',
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
